#!/usr/bin/env bash
# Proof of the v1 safety guards (spec: docs/specs/2026-06-11-harness-manager-v1.md §4):
#   H. incumbent hook-manager guard — init refuses, before touching anything
#   I. guarded cut-over — --cut-over refuses without OMAKASE_CUTOVER_CONFIRM=1
#   J. upstream-collision guard — a placed path turning TRACKED warns loudly
#   K. fail-closed gates — a wiped overlay BLOCKS commits instead of passing silently
#   L. worktree support — init works where $ROOT/.git is a file (linked worktree)
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INIT="$HERE/../bin/init.sh"
REMOVE="$HERE/../bin/remove.sh"
LEFTHOOK="${LEFTHOOK_BIN:-/Users/ericshen/Claude/pixterm-engine/node_modules/.bin/lefthook}"
TMP="${TMPDIR:-/tmp}/omakase-safety-test.$$"
FAILED=0
pass(){ echo "  PASS: $1"; }
fail(){ echo "  FAIL: $1"; FAILED=1; }

mkpayload(){ # $1 = payload dir
  local p="$1"
  mkdir -p "$p/.omakase/gates"
  cat > "$p/.omakase/gates/example.sh" <<'SH'
#!/usr/bin/env bash
echo "omakase-example-gate-ran"
exit 0
SH
  cat > "$p/lefthook-local.yml" <<'YML'
pre-commit:
  jobs:
    - name: omakase-example
      run: bash .omakase/gates/example.sh
post-checkout:
  jobs:
    - name: omakase-ensure-present
      run: bash "$(git rev-parse --git-common-dir)/omakase/ensure-present.sh"
YML
}

newrepo(){ rm -rf "$1"; mkdir -p "$1"; ( cd "$1" && git init -q && git config user.email t@t && git config user.name t && git config commit.gpgsign false && git commit -q --allow-empty -m init ); }

export PATH="$(dirname "$LEFTHOOK"):$PATH"

# ---------- Scenario H: incumbent hook-manager guard ----------
echo "== Scenario H: init refuses when an incumbent hook manager is present =="
PAY="$TMP/payH"; mkpayload "$PAY"

# H1: husky directory — refuse before any mutation
REPO="$TMP/repoH1"; newrepo "$REPO"; mkdir -p "$REPO/.husky"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "refused on .husky/ (exit $rc)" || fail "did not refuse on .husky/"
echo "$OUT" | grep -qi 'husky' && pass "refusal names husky" || fail "refusal does not name husky ($OUT)"
[ ! -e "$REPO/.omakase" ] && pass "placed nothing before refusing" || fail "placed files despite refusal"
grep -q "omakase-harness" "$REPO/.git/info/exclude" 2>/dev/null && fail "wrote exclude block despite refusal" || pass "exclude block untouched"
[ ! -f "$REPO/.git/hooks/pre-commit" ] && pass "no hook stub installed" || fail "hook stub installed despite refusal"

# H2: package.json "prepare": "husky" (reinstalls husky over lefthook on npm install)
REPO="$TMP/repoH2"; newrepo "$REPO"
printf '{ "scripts": { "prepare": "husky" } }\n' > "$REPO/package.json"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'husky'; } && pass "refused on package.json prepare:husky" || fail "did not refuse on prepare:husky ($OUT)"

# H3: foreign core.hooksPath (husky v9 sets .husky/_)
REPO="$TMP/repoH3"; newrepo "$REPO"
( cd "$REPO" && git config core.hooksPath .husky/_ )
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -q 'core.hooksPath'; } && pass "refused on foreign core.hooksPath, named it" || fail "did not refuse on core.hooksPath ($OUT)"

# H4: pre-commit framework — config file + installed stub in .git/hooks
REPO="$TMP/repoH4"; newrepo "$REPO"
printf 'repos: []\n' > "$REPO/.pre-commit-config.yaml"
printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n' > "$REPO/.git/hooks/pre-commit"
chmod +x "$REPO/.git/hooks/pre-commit"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'pre-commit'; } && pass "refused on installed pre-commit framework" || fail "did not refuse on pre-commit framework ($OUT)"

# H5: a plain hand-written hook file — refuse, and leave it exactly in place
REPO="$TMP/repoH5"; newrepo "$REPO"
printf '#!/bin/sh\necho team-gate\nexit 1\n' > "$REPO/.git/hooks/pre-push"; chmod +x "$REPO/.git/hooks/pre-push"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "refused on an existing non-lefthook hook file" || fail "did not refuse on a foreign hook file"
grep -q 'team-gate' "$REPO/.git/hooks/pre-push" 2>/dev/null && pass "incumbent hook left untouched (not displaced to .old)" || fail "incumbent hook was displaced"

# H6: no false positives — samples-only repo installs; re-init tolerates lefthook's own stubs
REPO="$TMP/repoH6"; newrepo "$REPO"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "clean repo (.sample hooks only) installs fine" || fail "refused a clean repo ($OUT)"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "re-init does not trip over lefthook's own stubs" || fail "re-init refused its own stubs ($OUT)"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$REMOVE" ) >/dev/null 2>&1

# H7: core.hooksPath pointing at the repo's OWN hooks dir is NOT an incumbent (the live
# pixterm-engine state). lefthook refuses to install while ANY core.hooksPath is set, so
# init clears the redundant entry (with a notice) and succeeds. Foreign stays refused (H3).
REPO="$TMP/repoH7"; newrepo "$REPO"
( cd "$REPO" && git config core.hooksPath .git/hooks )
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "own .git/hooks hooksPath (relative): init succeeds" || fail "false positive on own hooks dir ($OUT)"
echo "$OUT" | grep -q 'redundant core.hooksPath' && pass "notice printed about clearing the redundant entry" || fail "no clearing notice ($OUT)"
( cd "$REPO" && git config --get core.hooksPath >/dev/null 2>&1 ) && fail "core.hooksPath left set" || pass "redundant core.hooksPath cleared"
OUT=$( cd "$REPO" && echo h7 > h7.txt && git add h7.txt && git commit -m h7 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'omakase-example-gate-ran'; } && pass "hooks live after the cleared-hooksPath init" || fail "hooks dead after init ($OUT)"
REPO="$TMP/repoH7b"; newrepo "$REPO"
( cd "$REPO" && git config core.hooksPath "$REPO/.git/hooks" )
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1; rc=$?
[ "$rc" -eq 0 ] && pass "own .git/hooks hooksPath (absolute): init succeeds" || fail "false positive on absolute own hooks dir"

# H8: "prepare": "simple-git-hooks" — same flip-flop as husky (its npm install
# overwrites .git/hooks directly, no .old)
REPO="$TMP/repoH8"; newrepo "$REPO"
printf '{ "scripts": { "prepare": "simple-git-hooks" } }\n' > "$REPO/package.json"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'simple-git-hooks'; } && pass "refused on prepare:simple-git-hooks" || fail "simple-git-hooks slipped through ($OUT)"

# H9: .husky exemption principle — omakase's injected artifacts are always UNTRACKED.
# A git-TRACKED .husky is the project's own and refuses even when the payload ships
# .husky; an untracked .husky matching the payload is ours and stays exempt.
PAYH="$TMP/payH9"; mkpayload "$PAYH"; mkdir -p "$PAYH/.husky"; printf '#!/bin/sh\ntrue\n' > "$PAYH/.husky/pre-commit"
REPO="$TMP/repoH9"; newrepo "$REPO"
mkdir -p "$REPO/.husky"; printf '#!/bin/sh\nnpx jest\n' > "$REPO/.husky/pre-commit"
( cd "$REPO" && git add .husky && git commit -q -m husky )
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAYH" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'git-tracked'; } && pass "tracked .husky refused even though the payload ships .husky" || fail "tracked .husky slipped through via the payload exemption ($OUT)"
REPO="$TMP/repoH9b"; newrepo "$REPO"
mkdir -p "$REPO/.husky"; printf '#!/bin/sh\ntrue\n' > "$REPO/.husky/pre-commit"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAYH" bash "$INIT" ) >/dev/null 2>&1; rc=$?
[ "$rc" -eq 0 ] && pass "untracked .husky matching the payload stays exempt (roundtrip)" || fail "untracked payload .husky wrongly refused"

# ---------- Scenario I: guarded cut-over ----------
echo "== Scenario I: guarded cut-over =="
PAY="$TMP/payI"; mkpayload "$PAY"; printf 'payload agents\n' > "$PAY/AGENTS.md"
REPO="$TMP/repoI"; newrepo "$REPO"
( cd "$REPO" && printf 'COMMITTED agents\n' > AGENTS.md && git add AGENTS.md && git commit -q -m team )

# I1: plain init skips the committed file and advises the GUARDED form, not the raw command
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 )
echo "$OUT" | grep -q 'cut-over' && pass "skip advice points at the guarded cut-over" || fail "skip advice does not mention cut-over ($OUT)"
echo "$OUT" | grep -q 'git rm --cached' && fail "raw 'git rm --cached' still advised by plain init" || pass "raw git rm --cached no longer advised by plain init"

# I2: --cut-over without confirmation refuses and mutates nothing
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" --cut-over 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "cut-over refused without OMAKASE_CUTOVER_CONFIRM (exit $rc)" || fail "cut-over proceeded without confirmation"
echo "$OUT" | grep -q 'AGENTS.md' && pass "refusal names the file it would untrack" || fail "refusal does not name the file ($OUT)"
echo "$OUT" | grep -qi 'EVERYONE' && pass "refusal states the shared consequence" || fail "no shared-consequence statement ($OUT)"
( cd "$REPO" && git ls-files --error-unmatch AGENTS.md >/dev/null 2>&1 ) && pass "AGENTS.md still tracked after refusal" || fail "refusal still untracked the file"
[ -z "$(cd "$REPO" && git status --porcelain)" ] && pass "nothing staged after refusal" || fail "refusal left staged changes"
grep -q 'COMMITTED agents' "$REPO/AGENTS.md" && pass "committed content untouched after refusal" || fail "refusal touched the committed file"

# I3: with confirmation — untracks, stages the deletion, injected copy takes over on disk
OUT=$( cd "$REPO" && OMAKASE_CUTOVER_CONFIRM=1 OMAKASE_PAYLOAD="$PAY" bash "$INIT" --cut-over 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "confirmed cut-over proceeds (exit 0)" || fail "confirmed cut-over failed ($OUT)"
( cd "$REPO" && git ls-files --error-unmatch AGENTS.md >/dev/null 2>&1 ) && fail "AGENTS.md still tracked after confirmed cut-over" || pass "AGENTS.md untracked"
( cd "$REPO" && git status --porcelain ) | grep -q '^D  AGENTS.md' && pass "deletion STAGED for the user to review + commit" || fail "no staged deletion in git status"
[ -f "$REPO/AGENTS.md" ] && pass "file stays on disk" || fail "file deleted from disk"
grep -q 'payload agents' "$REPO/AGENTS.md" && pass "injected copy took over the path" || fail "injected copy did not take over"

# I4: --cut-over with nothing tracked is a no-op that still inits
REPO2="$TMP/repoI2"; newrepo "$REPO2"
OUT=$( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" --cut-over 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -qi 'nothing to cut over'; } && pass "cut-over with nothing tracked: no-op, init proceeds" || fail "empty cut-over mishandled ($OUT)"

# I5: --help documents the escape hatch
OUT=$( bash "$INIT" --help 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'cut-over' && echo "$OUT" | grep -q 'OMAKASE_CUTOVER_CONFIRM'; } && pass "--help documents --cut-over + the confirmation env" || fail "--help missing cut-over docs ($OUT)"

# ---------- Scenario J: upstream-collision guard ----------
echo "== Scenario J: a placed path turning TRACKED warns loudly =="
PAY="$TMP/payJ"; mkpayload "$PAY"
REPO="$TMP/repoJ"; newrepo "$REPO"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
COMMON="$(cd "$REPO" && cd "$(git rev-parse --git-common-dir)" && pwd)"
# Simulate an upstream commit landing a tracked file at a placed path (same end state
# as a pull: the index tracks the path, the working copy is upstream's content).
( cd "$REPO" && printf 'UPSTREAM CONTENT\n' > .omakase/gates/example.sh && git add -f .omakase/gates/example.sh && LEFTHOOK=0 git commit -q -m upstream )

# J1: the post-checkout self-heal warns (the timely surface) and never touches the tracked file
ERR=$( cd "$REPO" && bash "$COMMON/omakase/ensure-present.sh" 2>&1 )
echo "$ERR" | grep -qi 'WARNING' && pass "ensure-present warns on the tracked collision" || fail "ensure-present silent on collision ($ERR)"
echo "$ERR" | grep -q '.omakase/gates/example.sh' && pass "ensure-present warning names the file" || fail "warning does not name the file ($ERR)"
echo "$ERR" | grep -qi 'clobber' && pass "warning says the personal copy was likely clobbered" || fail "warning missing the clobber explanation ($ERR)"
grep -q 'UPSTREAM CONTENT' "$REPO/.omakase/gates/example.sh" && pass "tracked file left untouched" || fail "self-heal touched a tracked file"

# J2: re-init warns too and preserves the last-injected copy before rebuilding the snapshot
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "re-init still completes (warn, not block)" || fail "re-init failed on collision ($OUT)"
echo "$OUT" | grep -qi 'WARNING' && pass "init warns on the placed->tracked path" || fail "init silent on collision ($OUT)"
echo "$OUT" | grep -q '.omakase/gates/example.sh' && pass "init warning names the file" || fail "init warning does not name the file ($OUT)"
echo "$OUT" | grep -qi 'clobber' && pass "init warning explains the likely clobber" || fail "init warning missing clobber explanation ($OUT)"
echo "$OUT" | grep -q 'clobbered/' && pass "init warning points at the preserved copy" || fail "init warning missing the preserved-copy path ($OUT)"
grep -q 'omakase-example-gate-ran' "$COMMON/omakase/clobbered/.omakase/gates/example.sh" 2>/dev/null && pass "last-injected copy preserved under clobbered/" || fail "preserved copy missing or wrong"

# J3: no false warning on a clean re-init
REPO2="$TMP/repoJ2"; newrepo "$REPO2"
( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
OUT=$( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 )
echo "$OUT" | grep -qi 'NOW TRACKED' && fail "false collision warning on a clean re-init ($OUT)" || pass "no false warning on a clean re-init"

# ---------- Scenario K: gates fail closed when the overlay is wiped ----------
echo "== Scenario K: fail-closed gates =="
PAY="$TMP/payK"; mkpayload "$PAY"
REPO="$TMP/repoK"; newrepo "$REPO"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
COMMON="$(cd "$REPO" && cd "$(git rev-parse --git-common-dir)" && pwd)"
grep -q 'omakase-harness fail-closed' "$REPO/.git/hooks/pre-commit" && pass "guard block inserted into the pre-commit stub" || fail "no guard block in the pre-commit stub"
[ -x "$COMMON/omakase/verify-overlay.sh" ] && pass "verify-overlay.sh written (executable)" || fail "verify-overlay.sh missing"

# K1: intact overlay — commit passes and the gate fires
OUT=$( cd "$REPO" && echo a > a.txt && git add a.txt && git commit -m a 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'omakase-example-gate-ran'; } && pass "intact overlay: commit passes, gate fires" || fail "intact overlay broken ($OUT)"

# K2: wiped overlay (git clean -fdx) — commit BLOCKED with a restore instruction
( cd "$REPO" && git clean -fdx ) >/dev/null 2>&1
OUT=$( cd "$REPO" && echo b > b.txt && git add b.txt && git commit -m b 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "wiped overlay: commit BLOCKED (exit $rc) — no silent pass" || fail "wiped overlay: commit passed (gates fail OPEN) ($OUT)"
echo "$OUT" | grep -qi 'restore' && pass "block message carries a restore instruction" || fail "no restore instruction ($OUT)"
echo "$OUT" | grep -q 'missing:' && pass "block message names the missing file(s)" || fail "missing files not named ($OUT)"

# K3: the advertised restore unblocks; the gate fires again
( cd "$REPO" && bash "$COMMON/omakase/ensure-present.sh" )
OUT=$( cd "$REPO" && git commit -m b2 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'omakase-example-gate-ran'; } && pass "after ensure-present restore: commit passes, gate fires" || fail "restore did not unblock ($OUT)"

# K4: re-init keeps exactly one guard block (idempotent strip-then-insert)
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
n=$(grep -c 'omakase-harness fail-closed >>>' "$REPO/.git/hooks/pre-commit")
[ "$n" -eq 1 ] && pass "re-init keeps exactly one guard block" || fail "guard blocks duplicated ($n)"

# K4b: lefthook's npm postinstall runs `lefthook install -f` on every npm/yarn install,
# regenerating the stubs and stripping the guard; the next checkout re-arms it
# (ensure-present calls install-guards.sh from the post-checkout job).
( cd "$REPO" && "$LEFTHOOK" install -f ) >/dev/null 2>&1
n=$(grep -c 'omakase-harness fail-closed >>>' "$REPO/.git/hooks/pre-commit")
[ "$n" -eq 0 ] && pass "lefthook install -f strips the guard (the reviewer's repro)" || fail "expected a stripped guard after install -f ($n)"
( cd "$REPO" && git checkout -q -b rearm ) 2>/dev/null
n=$(grep -c 'omakase-harness fail-closed >>>' "$REPO/.git/hooks/pre-commit")
[ "$n" -eq 1 ] && pass "post-checkout re-arms the guard after stub regeneration" || fail "guard not re-armed by checkout ($n)"

# K5: a fresh MANUAL worktree (harness files not yet copied in) fails closed too —
# before this guard, gates silently did not run there; the block's restore command heals it.
REPO2="$TMP/repoK2"; newrepo "$REPO2"
( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
COMMON2="$(cd "$REPO2" && cd "$(git rev-parse --git-common-dir)" && pwd)"
WT="$TMP/repoK2-wt"
( cd "$REPO2" && git worktree add -q "$WT" -b wtsafety ) 2>/dev/null
OUT=$( cd "$WT" && echo w > w.txt && git add w.txt && git commit -m w 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "fresh manual worktree: commit BLOCKED instead of gates silently not running" || fail "fresh worktree committed without gates ($OUT)"
( cd "$WT" && bash "$COMMON2/omakase/ensure-present.sh" )
OUT=$( cd "$WT" && git commit -m w2 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'omakase-example-gate-ran'; } && pass "ensure-present heals the worktree; commit passes with the gate firing" || fail "worktree heal did not unblock ($OUT)"
( cd "$REPO2" && git worktree remove --force "$WT" ) 2>/dev/null; ( cd "$REPO2" && git worktree prune ) 2>/dev/null

# K6: after remove, commits are not blocked (guard gone or inert)
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$REMOVE" ) >/dev/null 2>&1
OUT=$( cd "$REPO" && echo c > c.txt && git add c.txt && git commit -m c 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "after remove: commits flow (fail-closed guard inert)" || fail "remove left a blocking guard ($OUT)"

# ---------- Scenario L: init runs clean from inside a linked worktree ----------
# $ROOT/.git is a FILE in a linked worktree, so an exclude path literally under
# "$ROOT/.git/info" crashes mkdir; it must resolve via the shared git dir. (The
# fail-closed block message recommends /omakase init from exactly this state.)
echo "== Scenario L: init from inside a linked worktree =="
PAY="$TMP/payL"; mkpayload "$PAY"
REPO="$TMP/repoL"; newrepo "$REPO"
WT="$TMP/repoL-wt"
( cd "$REPO" && git worktree add -q "$WT" -b wtinit ) 2>/dev/null
OUT=$( cd "$WT" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "init inside a linked worktree exits 0" || fail "worktree init crashed ($OUT)"
[ -x "$WT/.omakase/gates/example.sh" ] && pass "gate placed into the worktree" || fail "gate missing in worktree"
grep -q 'omakase-harness' "$REPO/.git/info/exclude" 2>/dev/null && pass "exclude block written to the SHARED git dir" || fail "exclude block missing from shared git dir"
[ -z "$(cd "$WT" && git status --porcelain)" ] && pass "worktree status clean (zero footprint)" || { fail "worktree status not clean"; (cd "$WT" && git status --porcelain | sed 's/^/      /'); }
OUT=$( cd "$WT" && echo l > l.txt && git add l.txt && git commit -m l 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'omakase-example-gate-ran'; } && pass "commit from the worktree fires the gate" || fail "gate did not fire from the worktree ($OUT)"
( cd "$REPO" && git worktree remove --force "$WT" ) 2>/dev/null; ( cd "$REPO" && git worktree prune ) 2>/dev/null

rm -rf "$TMP"
echo ""
[ "$FAILED" -eq 0 ] && echo "ALL PASS" || { echo "FAILURES PRESENT"; exit 1; }
